-- CreateTable
CREATE TABLE "categories" (
    "categoryId" INTEGER NOT NULL,
    "categoryName" TEXT NOT NULL,
    "metaKeywords" TEXT,
    "metaTitle" TEXT,
    "description" TEXT,
    "metaDescription" TEXT,
    "parentCategoryId" INTEGER,
    "pictureId" INTEGER,
    "pageSize" INTEGER,
    "showOnHomepage" TEXT,
    "includeInTopMenu" TEXT,
    "isDeleted" TEXT,
    "displayOrder" INTEGER,
    "isActive" TEXT,
    "categoryUrl" TEXT,
    "imagePath" TEXT,
    "breadcrumbCategory" TEXT,
    "levelNo" TEXT,
    "isProduct" TEXT,
    "isReturnable" TEXT,
    "localCmsnPercentage" DOUBLE PRECISION,
    "localCmsnFlatAmt" DOUBLE PRECISION,
    "globalCmsnPercentage" DOUBLE PRECISION,
    "globalCmsnFlatAmt" DOUBLE PRECISION,
    "isPopular" TEXT,
    "isNewArrival" TEXT,
    "isTopCategory" TEXT,
    "repalceCategoryUrl" TEXT,
    "brandId" INTEGER,
    "brandName" TEXT,
    "metaLongDescription" TEXT,
    "ogType" TEXT,
    "ogTitle" TEXT,
    "ogDescription" TEXT,
    "ogUrl" TEXT,
    "ogImgUrl" TEXT,
    "totalItems" INTEGER,
    "createdBy" TEXT,
    "createDate" TEXT,
    "updateBy" TEXT,
    "updateDate" TEXT,

    CONSTRAINT "categories_pkey" PRIMARY KEY ("categoryId")
);
