-- CreateTable
CREATE TABLE "products" (
    "productId" INTEGER NOT NULL,
    "productName" TEXT NOT NULL,
    "categoryId" INTEGER NOT NULL,
    "unit" TEXT,
    "shopId" INTEGER,
    "displayOrder" TEXT,
    "thumbnailImages" JSONB,
    "brandId" INTEGER,
    "strapMeterial" TEXT,
    "fitType" TEXT,
    "gender" TEXT,
    "variantDimensions" JSONB,
    "variantImages" JSONB,
    "variantCombinations" JSONB,
    "sku" TEXT,
    "subStyle" TEXT,
    "stock" INTEGER,
    "dpPrice" DOUBLE PRECISION,
    "mrp" DOUBLE PRECISION,
    "sellingPrice" DOUBLE PRECISION,
    "startDate" TEXT,
    "endDate" TEXT,
    "description" TEXT,
    "specification" TEXT,
    "hasEmi" TEXT,
    "isReturnable" TEXT,
    "returnDuration" INTEGER,
    "returnPolicy" TEXT,
    "sizeChartId" INTEGER,
    "warrantyTypeId" INTEGER,
    "warrantyPeriodId" INTEGER,
    "warrantyPolicy" TEXT,
    "packageWeight" DOUBLE PRECISION,
    "packageLength" DOUBLE PRECISION,
    "packageWidth" DOUBLE PRECISION,
    "packageHeight" DOUBLE PRECISION,
    "productUrl" TEXT,
    "videoUrl" TEXT,
    "metaTitle" TEXT,
    "metaKeywords" TEXT,
    "metaDescription" TEXT,
    "ogType" TEXT,
    "ogTitle" TEXT,
    "ogUrl" TEXT,
    "ogDescription" TEXT,
    "ogImage" TEXT,
    "createdBy" TEXT,
    "createdAt" TEXT,
    "updatedBy" TEXT,
    "updatedAt" TEXT,

    CONSTRAINT "products_pkey" PRIMARY KEY ("productId")
);
